#!/bin/bash
#
# SLURM recovery job for QAOA-XORSAT: re-run overflowed (k,D) pairs.
# Generated by recover-run.py — re-run this script to regenerate.
#
#SBATCH --job-name=qaoa-recovery
#SBATCH --array=1-15
#SBATCH --partition=c3d
#SBATCH --time=999:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=28
#SBATCH --mem=2700G
#SBATCH --output=qaoa-recovery_%A-%a.out
#SBATCH --error=qaoa-recovery_%A-%a.err

set -euo pipefail

THREADS="${SLURM_CPUS_PER_TASK:-28}"

# Task ID → TOML config mapping
declare -a CONFIGS=(
    "experiments/recovery/k3-d4.toml"  # 1: k=3, D=4, resume from p=13
    "experiments/recovery/k3-d5.toml"  # 2: k=3, D=5, resume from p=1
    "experiments/recovery/k3-d6.toml"  # 3: k=3, D=6, resume from p=1
    "experiments/recovery/k3-d7.toml"  # 4: k=3, D=7, resume from p=1
    "experiments/recovery/k3-d8.toml"  # 5: k=3, D=8, resume from p=1
    "experiments/recovery/k4-d5.toml"  # 6: k=4, D=5, resume from p=1
    "experiments/recovery/k4-d6.toml"  # 7: k=4, D=6, resume from p=1
    "experiments/recovery/k4-d7.toml"  # 8: k=4, D=7, resume from p=1
    "experiments/recovery/k4-d8.toml"  # 9: k=4, D=8, resume from p=1
    "experiments/recovery/k5-d6.toml"  # 10: k=5, D=6, resume from p=1
    "experiments/recovery/k5-d7.toml"  # 11: k=5, D=7, resume from p=1
    "experiments/recovery/k5-d8.toml"  # 12: k=5, D=8, resume from p=1
    "experiments/recovery/k6-d7.toml"  # 13: k=6, D=7, resume from p=1
    "experiments/recovery/k6-d8.toml"  # 14: k=6, D=8, resume from p=1
    "experiments/recovery/k7-d8.toml"  # 15: k=7, D=8, resume from p=1
)

TASK_INDEX=$((SLURM_ARRAY_TASK_ID - 1))
CONFIG="${CONFIGS[$TASK_INDEX]}"

echo "=== QAOA-XORSAT Recovery ==="
echo "Job ID:    ${SLURM_JOB_ID:-local}"
echo "Array ID:  $SLURM_ARRAY_TASK_ID"
echo "Config:    $CONFIG"
echo "Node:      $(hostname)"
echo "Started:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

cd ~/qaoa-xorsat

julia --project=. -t "$THREADS" scripts/optimize_qaoa.jl "$CONFIG"

echo ""
echo "Finished: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
